import argparse
import subprocess
import os

def addZeros(pathName, size):
    '''
    Add zeros to a filename or dirname

            Parameters:
                    pathName (string): name of the directory of file
                    size (int) : number of zeros that be to added to the name

            Returns:
                    pathName (string): the name of the file or directory in the good format
    '''
    while len(pathName) < size:
        pathName = "0" + pathName
    return pathName

def createFile(path, nbOfBits):
    '''
    Create file

            Parameters:
                    path (string): path of the files
                    nbOfBits (int) : number of bits to be generated by the random function
    '''
    newFile = open(path, "w")
    newFile.write(random(nbOfBits))
    newFile.close()

def generate(dirname):
    '''
    Generate 100 pads in a subfolder of the directory specified in the position argument, the directory must contains less than 9999 directories 

            Parameters:
                    dirname (string): name of the position argument, the directory
    '''
    createDirectory(dirname)
    nbOfFiles = subprocess.check_output("ls -1 "+dirname+" | wc -l", shell=True)
    directoryNumber = addZeros(str(int(nbOfFiles)), 4)
    createDirectory(dirname + "/" + directoryNumber)
    if nbOfFiles < 9999:
        for i in range(100):
            fileNumber = addZeros(str(i), 2)
            path = dirname + "/" + directoryNumber + "/" + fileNumber
            for j in range(3):
                if j == 0:
                    createFile(path + "p", 48)
                elif j == 1:
                    createFile(path + "c", 2000)

                else:
                    createFile(path + "s", 48)

        
        createDirectory("receiver/" + dirname)
        subprocess.call("cp -r "+ dirname + "/" + directoryNumber+ "/ receiver/" + dirname +"/", shell=True)
    else:
        print("Number of file in the directory " + dirname + " is too big: >= 9999")

def random(size):
    '''
    Generate n random binary number 

            Parameters:
                    size (int): size of the list of binary number in bytes
            Returns:
                    listOfRandomNumber (string): list of random binary number
    '''
    listOfRandomNumber = ""
    with open("/dev/urandom", 'rb') as f:       
        for i in range(size):
            listOfRandomNumber += convertIntToBinary(int.from_bytes(f.read(1), 'big'))
    return listOfRandomNumber

def convertIntToBinary(number):
    '''
    Convert an integer in base 2

            Parameters:
                    number (int): a integer to convert

            Returns:
                    binaryNumber (string): the convertion of integer in base 2 with 8 bits.
    '''

    binaryNumber = '{0:08b}'.format(number)
    return binaryNumber

def convertToAsciiBinary(text):
    '''
    Convert an acsii in base 2

            Parameters:
                    text (string): the text to convert

            Returns:
                    binaryText (string): the convertion of the text in base 2 with 8 bits.
    '''

    binaryText = ""
    for letter in text:
        binaryLetter = convertIntToBinary(ord(letter))
        binaryText += binaryLetter
    return binaryText


def createDirectory(dirname):
    '''
    Create directory

            Parameters:
                    dirname (string): name of the directory that will be created
    '''
    os.makedirs(dirname, exist_ok=True)

def sendText(text):
    path = dirname
    nbFile = subprocess.check_output("ls -1 "+dirname+" | wc -l", shell=True)

    for i in range(int(nbFile)):
        directoryNumber = str(i)
        while len(directoryNumber) < 4:
            directoryNumber = "0" + directoryNumber
        path += "/" + directoryNumber 
        for j in range(100):
            fileNumber = str(i)
            while len(fileNumber) < 2:
                fileNumber = "0" + fileNumber
            if os.path.exists(path + "/" + fileNumber + "c") :
                # path += "/" + fileNumber
                print(fileNumber)
                break
        break

    f = open(path + "/" + fileNumber + "c", "r")
    padC = f.read()
    f.close()

    textEncoded = ""
    print(len(text))
    for i in range(int(len(text)/8)):
        number = int(text[i*8:i*8+8], 2) + int(padC[i*8:i*8+8], 2)
        print("1 : ", int(text[i*8:i*8+8], 2))
        print("2 : ", int(padC[i*8:i*8+8], 2))
        print("3 : ", number)
        textEncoded += '{0:09b}'.format(number)
    
    f = open(path + "/" + fileNumber + "p", "r")
    padP = f.read()
    f.close()

    f = open(path + "/" + fileNumber + "s", "r")
    padS = f.read()
    f.close()


    print(textEncoded)
    textInFileT = padP + textEncoded + padS
    print(len(textInFileT))
    fichier = open(dirname+"-"+directoryNumber+"-"+fileNumber+"t", "w")

    fichier.write(textInFileT)
    fichier.close()
    
def receiveText(text):
    prefix = text[:384]
    suffix = text[-384:]
    message = text[384:-384]
    
    path = "receiver/"+dirname
    nbFile = subprocess.check_output("ls -1 receiver/"+dirname+" | wc -l", shell=True)

    for i in range(int(nbFile)):
        directoryNumber = str(i)
        while len(directoryNumber) < 4:
            directoryNumber = "0" + directoryNumber
        path += "/" + directoryNumber 
        for j in range(100):
            fileNumber = str(i)
            while len(fileNumber) < 2:
                fileNumber = "0" + fileNumber
            if os.path.exists(path + "/" + fileNumber + "p") :
                f = open(path + "/" + fileNumber + "p", "r")
                padP = f.read()
                f.close()
                if padP == prefix:
                    f = open(path + "/" + fileNumber + "c", "r")
                    padC = f.read()
                    f.close()
                    textEncoded = ""
                    for m in range(int(len(message)/9)):
                        a = int(message[m*9:m*9+9], 2)
                        b = int(padC[m*8:m*8+8], 2)
                        c = a - b
                        c = convertIntToBinary(c)
                        number = int(message[m*9:m*9+9], 2) - int(padC[m*8:m*8+8], 2)
                        textEncoded += chr(int(c, 2))
                    print(textEncoded)
                break         
        break

if __name__ == "__main__": 
    parser = argparse.ArgumentParser(description = "Write or read text in a PNG file")
    parser.add_argument("-g", type = str, help = "text to write in the PNG")
    parser.add_argument("-s", type = str, help = "file to write in the PNG")
    parser.add_argument("-r", type = str, help = "file to write in the PNG")
    parser.add_argument("-t", type = str, help = "text to write in the PNG")
    parser.add_argument("-f", type = str, help = "file to write in the PNG")
    args = parser.parse_args()


    if args.s:
        print("Send")
        if args.t:
            text = args.t
        elif args.f:
            textInFile = open(args.f, "r")
            text = textInFile.read()
            textInFile.close()
        else:
            text = input("Enter your text : ")

        text = convertToAsciiBinary(text) + "00000011"
        if len(text) > 2000:
            raise Exception('the length of the text is too big and not exceed 2000 bytes. The length was: {}'.format(len(text)))
        print("halloS")
        sendText(text)
    elif args.r:
        print("Receive")
        textInFile = open(args.r, "r")
        text = textInFile.read()
        textInFile.close()
        receiveText(text)

    elif args.g:
        dirname = args.g
        print ("Generate")
        generate(dirname)